### PR TITLE
add erlang language

### PR DESCRIPTION
**Pull request by meppu**
I added erlang icon which respects current color theme.

### CODE REVIEW

**Comment by meppu** [comment]
fixed merge conflict

**Comment by miguelsolorio** [comment]
Thanks for the PR, I am not a huge fan of that logo, I might play around with some alternate options. I do like how Material Icons has it inverted:

CleanShot 2023-05-01 at 11 51 10@2x

Also, it looks like you had formatted some sections in the code. Do you mind undoing those changes?

**Comment by meppu** [comment]
> Also, it looks like you had formatted some sections in the code. Do you mind undoing those changes?
Yeah i use format on save so that's probably why

> Thanks for the PR, I am not a huge fan of that logo, I might play around with some alternate options.
Yeah i know it is a bad logo, this is the best i can find (from simple icons)

**Comment by meppu** [comment]
Also i think it might be a good idea to mark `file-type/` folder as vendored so linguist will not show them on languages bar (currently shows %4.3 solidity for example) like this:

*File name: .gitattributes*
```gitattributes
file-type/** linguist-vendored
```

I can commit it quickly if you want 😅

**Comment by miguelsolorio** [comment]
Updated the icon to be inverted and use our existing colors. Thanks for the PR!

CleanShot 2023-05-05 at 08 59 15@2x

**Pull request merged**
