### PR TITLE
Feature: Toggle Explorer Arrows Configuration

### PR DESCRIPTION
**Pull request by barelyhuman**
- [x] ~~register command to handle arrow toggling~~, removed since it adds a lot of complexity to a simple change which can be a lot easily handled by just changing the configuration
- [x] split up into maintainable modules
- [x] ~~move `.json` to `.default.json` for the default settings and generate a new `.json` from it when the theme is first activated~~ , added an ignored file `.modified.json` that vscode will look for so the source stays as is
- [x] add a listener for configuration changes to make this portable 

Adds to the vscode configuration

```json
"symbols.hidesExplorerArrows":true
```

### CODE REVIEW

**Comment by barelyhuman** [comment]
The force-push only edits one commit [`0c6c832`](https://github.com/misolori/vscode-symbols/pull/8/commits/0c6c8326ba4a6dc6edffb3295c37e514dab6b515), since changes were added to main yesterday that weren't in the fork and the mentioned commit removed trailing commas in the JSON

**Review by misolori — APPROVED** [review]
This is a huge PR, thank you so much for tackling this! Made some minor changes and show a notification when the change has been made to ask users to reload.

**Comment by misolori** [comment]
@barelyhuman one issue I am seeing is that if `symbol-icon-theme.modified.json` already exists, when you make changes to `symbol-icon-theme.json` the modified file does not get updated. It's almost like we need to do cleanup when activating the extension. Would you be able to add this?

**Comment by barelyhuman** [comment]
i guess I totally forgot about handling updates in the theme, will add a sync on activation to check for new props. 

Should be able to raise a PR around noon tomorrow

**Pull request merged**
